export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const LOAD_FAIL = "LOAD_FAIL";

export const LOGOUT = "LOGOUT";

export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";

export const ALL_CATEGORIES_SUCCESS = "ALL_CATEGORIES_SUCCESS";
export const ALL_CATEGORIES_FAIL = "ALL_CATEGORIES_FAIL";

export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAIL = "ADD_POST_FAIL";

export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAIL = "SEARCH_FAIL";

export const VISIT_PROFILE_SUCCESS = "VISIT_PROFILE_SUCCESS";
export const VISIT_PROFILE_FAIL = "VISIT_PROFILE_FAIL";

export const SEND_REQUEST_SUCCESS = "SEND_REQUEST_SUCCESS";
export const SEND_REQUEST_FAIL = "SEND_REQUEST_FAIL";

export const CHECK_REQUESTS_CLIENT_SUCCESS = "CHECK_REQUESTS_CLIENT_SUCCESS";
export const CHECK_REQUESTS_CLIENT_FAIL = "CHECK_REQUESTS_CLIENT_FAIL";

export const CHECK_REQUESTS_ARTISAN_SUCCESS = "CHECK_REQUESTS_ARTISAN_SUCCESS";
export const CHECK_REQUESTS_ARTISAN_FAIL = "CHECK_REQUESTS_ARTISAN_FAIL";

export const RESPONSE_ARTISAN_SUCCESS = "RESPONSE_ARTISAN_SUCCESS";
export const RESPONSE_ARTISAN_FAIL = "RESPONSE_ARTISAN_FAIL";

export const IGNORE_REQUEST_SUCCESS = "IGNORE_REQUEST_SUCCESS";
export const IGNORE_REQUEST_FAIL = "IGNORE_REQUEST_FAIL";

export const REJECT_REQUEST_SUCCESS = "REJECT_REQUEST_SUCCESS";
export const REJECT_REQUEST_FAIL = "REJECT_REQUEST_FAIL";

export const ACCEPT_REQUEST_SUCCESS = "ACCEPT_REQUEST_SUCCESS";
export const ACCEPT_REQUEST_FAIL = "ACCEPT_REQUEST_FAIL";

export const RATING_SUCCESS = "RATING_SUCCESS";
export const RATING_FAIL = "RATING_FAIL";

export const GET_RATING_CLIENT_SUCCESS = "GET_RATING_CLIENT_SUCCESS";
export const GET_RATING_CLIENT_FAIL = "GET_RATING_CLIENT_FAIL";

export const GET_RATES_ARTISAN_SUCCESS = "GET_RATES_ARTISAN_SUCCESS";
export const GET_RATES_ARTISAN_FAIL = "GET_RATES_ARTISAN_FAIL";

export const GET_POSTS_ARTISAN_SUCCESS = "GET_POSTS_ARTISAN_SUCCESS";
export const GET_POSTS_ARTISAN_FAIL = "GET_POSTS_ARTISAN_FAIL";

export const UPDATE_INFO_SUCCESS = "UPDATE_INFO_SUCCESS";
export const UPDATE_INFO_FAIL = "UPDATE_INFO_FAIL";

export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const ADD_PHOTO_SUCCESS = "ADD_PHOTO_SUCCESS";
export const ADD_PHOTO_FAIL = "ADD_PHOTO_FAIL";

export const ADD_LIKE_SUCCESS = "ADD_LIKE_SUCCESS";
export const ADD_LIKE_FAIL = "ADD_LIKE_FAIL";

export const DELETE_LIKE_SUCCESS = "DELETE_LIKE_SUCCESS";
export const DELETE_LIKE_FAIL = "DELETE_LIKE_FAIL";

export const GET_LIKES_ARTISAN_SUCCESS = "GET_LIKES_ARTISAN_SUCCESS";
export const GET_LIKES_ARTISAN_FAIL = "GET_LIKES_ARTISAN_FAIL";

export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";

export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";
